/* Auto-generated by genmsg_cpp for file /home/bardo91/programing/ROS-CATEC/CATEC_dataTypes/catec_actions_msgs/msg/AALExtensionActionResult.msg */
#ifndef CATEC_ACTIONS_MSGS_MESSAGE_AALEXTENSIONACTIONRESULT_H
#define CATEC_ACTIONS_MSGS_MESSAGE_AALEXTENSIONACTIONRESULT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace catec_actions_msgs
{
template <class ContainerAllocator>
struct AALExtensionActionResult_ {
  typedef AALExtensionActionResult_<ContainerAllocator> Type;

  AALExtensionActionResult_()
  : result(0)
  {
  }

  AALExtensionActionResult_(const ContainerAllocator& _alloc)
  : result(0)
  {
  }

  typedef uint8_t _result_type;
  uint8_t result;

  enum { ALREADY_EXTENDED = 1 };
  enum { ALREADY_CONTRACTED = 2 };
  enum { EXTENDED = 3 };
  enum { CONTRACTED = 4 };
  enum { IMPOSIBLE = 5 };

  typedef boost::shared_ptr< ::catec_actions_msgs::AALExtensionActionResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::catec_actions_msgs::AALExtensionActionResult_<ContainerAllocator>  const> ConstPtr;
}; // struct AALExtensionActionResult
typedef  ::catec_actions_msgs::AALExtensionActionResult_<std::allocator<void> > AALExtensionActionResult;

typedef boost::shared_ptr< ::catec_actions_msgs::AALExtensionActionResult> AALExtensionActionResultPtr;
typedef boost::shared_ptr< ::catec_actions_msgs::AALExtensionActionResult const> AALExtensionActionResultConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::catec_actions_msgs::AALExtensionActionResult_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::catec_actions_msgs::AALExtensionActionResult_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace catec_actions_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::catec_actions_msgs::AALExtensionActionResult_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::catec_actions_msgs::AALExtensionActionResult_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::catec_actions_msgs::AALExtensionActionResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "2fb4b1a4c33faf9829300760a94b2904";
  }

  static const char* value(const  ::catec_actions_msgs::AALExtensionActionResult_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x2fb4b1a4c33faf98ULL;
  static const uint64_t static_value2 = 0x29300760a94b2904ULL;
};

template<class ContainerAllocator>
struct DataType< ::catec_actions_msgs::AALExtensionActionResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "catec_actions_msgs/AALExtensionActionResult";
  }

  static const char* value(const  ::catec_actions_msgs::AALExtensionActionResult_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::catec_actions_msgs::AALExtensionActionResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#result definition\n\
uint8 ALREADY_EXTENDED=1\n\
uint8 ALREADY_CONTRACTED=2\n\
uint8 EXTENDED=3\n\
uint8 CONTRACTED=4\n\
uint8 IMPOSIBLE=5\n\
uint8 result\n\
\n\
";
  }

  static const char* value(const  ::catec_actions_msgs::AALExtensionActionResult_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::catec_actions_msgs::AALExtensionActionResult_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::catec_actions_msgs::AALExtensionActionResult_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.result);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct AALExtensionActionResult_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::catec_actions_msgs::AALExtensionActionResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::catec_actions_msgs::AALExtensionActionResult_<ContainerAllocator> & v) 
  {
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};


} // namespace message_operations
} // namespace ros

#endif // CATEC_ACTIONS_MSGS_MESSAGE_AALEXTENSIONACTIONRESULT_H

