/* Auto-generated by genmsg_cpp for file /home/bardo91/programing/ROS-CATEC/CATEC_dataTypes/catec_actions_msgs/msg/BatteryRechargeGoal.msg */
#ifndef CATEC_ACTIONS_MSGS_MESSAGE_BATTERYRECHARGEGOAL_H
#define CATEC_ACTIONS_MSGS_MESSAGE_BATTERYRECHARGEGOAL_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace catec_actions_msgs
{
template <class ContainerAllocator>
struct BatteryRechargeGoal_ {
  typedef BatteryRechargeGoal_<ContainerAllocator> Type;

  BatteryRechargeGoal_()
  {
  }

  BatteryRechargeGoal_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::catec_actions_msgs::BatteryRechargeGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::catec_actions_msgs::BatteryRechargeGoal_<ContainerAllocator>  const> ConstPtr;
}; // struct BatteryRechargeGoal
typedef  ::catec_actions_msgs::BatteryRechargeGoal_<std::allocator<void> > BatteryRechargeGoal;

typedef boost::shared_ptr< ::catec_actions_msgs::BatteryRechargeGoal> BatteryRechargeGoalPtr;
typedef boost::shared_ptr< ::catec_actions_msgs::BatteryRechargeGoal const> BatteryRechargeGoalConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::catec_actions_msgs::BatteryRechargeGoal_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::catec_actions_msgs::BatteryRechargeGoal_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace catec_actions_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::catec_actions_msgs::BatteryRechargeGoal_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::catec_actions_msgs::BatteryRechargeGoal_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::catec_actions_msgs::BatteryRechargeGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::catec_actions_msgs::BatteryRechargeGoal_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::catec_actions_msgs::BatteryRechargeGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "catec_actions_msgs/BatteryRechargeGoal";
  }

  static const char* value(const  ::catec_actions_msgs::BatteryRechargeGoal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::catec_actions_msgs::BatteryRechargeGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal definition\n\
\n\
\n\
";
  }

  static const char* value(const  ::catec_actions_msgs::BatteryRechargeGoal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::catec_actions_msgs::BatteryRechargeGoal_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::catec_actions_msgs::BatteryRechargeGoal_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct BatteryRechargeGoal_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::catec_actions_msgs::BatteryRechargeGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::catec_actions_msgs::BatteryRechargeGoal_<ContainerAllocator> & v) 
  {
  }
};


} // namespace message_operations
} // namespace ros

#endif // CATEC_ACTIONS_MSGS_MESSAGE_BATTERYRECHARGEGOAL_H

