/* Auto-generated by genmsg_cpp for file /home/bardo91/programing/ROS-CATEC/CATEC_dataTypes/catec_actions_msgs/msg/BatteryRechargeResult.msg */
#ifndef CATEC_ACTIONS_MSGS_MESSAGE_BATTERYRECHARGERESULT_H
#define CATEC_ACTIONS_MSGS_MESSAGE_BATTERYRECHARGERESULT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace catec_actions_msgs
{
template <class ContainerAllocator>
struct BatteryRechargeResult_ {
  typedef BatteryRechargeResult_<ContainerAllocator> Type;

  BatteryRechargeResult_()
  : battery_level(0)
  {
  }

  BatteryRechargeResult_(const ContainerAllocator& _alloc)
  : battery_level(0)
  {
  }

  typedef uint32_t _battery_level_type;
  uint32_t battery_level;


  typedef boost::shared_ptr< ::catec_actions_msgs::BatteryRechargeResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::catec_actions_msgs::BatteryRechargeResult_<ContainerAllocator>  const> ConstPtr;
}; // struct BatteryRechargeResult
typedef  ::catec_actions_msgs::BatteryRechargeResult_<std::allocator<void> > BatteryRechargeResult;

typedef boost::shared_ptr< ::catec_actions_msgs::BatteryRechargeResult> BatteryRechargeResultPtr;
typedef boost::shared_ptr< ::catec_actions_msgs::BatteryRechargeResult const> BatteryRechargeResultConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::catec_actions_msgs::BatteryRechargeResult_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::catec_actions_msgs::BatteryRechargeResult_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace catec_actions_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::catec_actions_msgs::BatteryRechargeResult_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::catec_actions_msgs::BatteryRechargeResult_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::catec_actions_msgs::BatteryRechargeResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "beb4f050e160a1cc8885c094ea62fd5f";
  }

  static const char* value(const  ::catec_actions_msgs::BatteryRechargeResult_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xbeb4f050e160a1ccULL;
  static const uint64_t static_value2 = 0x8885c094ea62fd5fULL;
};

template<class ContainerAllocator>
struct DataType< ::catec_actions_msgs::BatteryRechargeResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "catec_actions_msgs/BatteryRechargeResult";
  }

  static const char* value(const  ::catec_actions_msgs::BatteryRechargeResult_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::catec_actions_msgs::BatteryRechargeResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#result definition\n\
uint32 battery_level\n\
\n\
";
  }

  static const char* value(const  ::catec_actions_msgs::BatteryRechargeResult_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::catec_actions_msgs::BatteryRechargeResult_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::catec_actions_msgs::BatteryRechargeResult_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.battery_level);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct BatteryRechargeResult_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::catec_actions_msgs::BatteryRechargeResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::catec_actions_msgs::BatteryRechargeResult_<ContainerAllocator> & v) 
  {
    s << indent << "battery_level: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.battery_level);
  }
};


} // namespace message_operations
} // namespace ros

#endif // CATEC_ACTIONS_MSGS_MESSAGE_BATTERYRECHARGERESULT_H

