/* Auto-generated by genmsg_cpp for file /home/bardo91/programing/ROS-CATEC/CATEC_dataTypes/catec_actions_msgs/msg/DownloadDataFeedback.msg */
#ifndef CATEC_ACTIONS_MSGS_MESSAGE_DOWNLOADDATAFEEDBACK_H
#define CATEC_ACTIONS_MSGS_MESSAGE_DOWNLOADDATAFEEDBACK_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace catec_actions_msgs
{
template <class ContainerAllocator>
struct DownloadDataFeedback_ {
  typedef DownloadDataFeedback_<ContainerAllocator> Type;

  DownloadDataFeedback_()
  : images_sent(0)
  , bytes_sent(0)
  {
  }

  DownloadDataFeedback_(const ContainerAllocator& _alloc)
  : images_sent(0)
  , bytes_sent(0)
  {
  }

  typedef uint8_t _images_sent_type;
  uint8_t images_sent;

  typedef uint32_t _bytes_sent_type;
  uint32_t bytes_sent;


  typedef boost::shared_ptr< ::catec_actions_msgs::DownloadDataFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::catec_actions_msgs::DownloadDataFeedback_<ContainerAllocator>  const> ConstPtr;
}; // struct DownloadDataFeedback
typedef  ::catec_actions_msgs::DownloadDataFeedback_<std::allocator<void> > DownloadDataFeedback;

typedef boost::shared_ptr< ::catec_actions_msgs::DownloadDataFeedback> DownloadDataFeedbackPtr;
typedef boost::shared_ptr< ::catec_actions_msgs::DownloadDataFeedback const> DownloadDataFeedbackConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::catec_actions_msgs::DownloadDataFeedback_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::catec_actions_msgs::DownloadDataFeedback_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace catec_actions_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::catec_actions_msgs::DownloadDataFeedback_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::catec_actions_msgs::DownloadDataFeedback_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::catec_actions_msgs::DownloadDataFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "34a6e94d0199c97c9a2459cd91b949d7";
  }

  static const char* value(const  ::catec_actions_msgs::DownloadDataFeedback_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x34a6e94d0199c97cULL;
  static const uint64_t static_value2 = 0x9a2459cd91b949d7ULL;
};

template<class ContainerAllocator>
struct DataType< ::catec_actions_msgs::DownloadDataFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "catec_actions_msgs/DownloadDataFeedback";
  }

  static const char* value(const  ::catec_actions_msgs::DownloadDataFeedback_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::catec_actions_msgs::DownloadDataFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#feedback definition\n\
uint8  images_sent\n\
uint32 bytes_sent\n\
\n\
\n\
";
  }

  static const char* value(const  ::catec_actions_msgs::DownloadDataFeedback_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::catec_actions_msgs::DownloadDataFeedback_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::catec_actions_msgs::DownloadDataFeedback_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.images_sent);
    stream.next(m.bytes_sent);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct DownloadDataFeedback_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::catec_actions_msgs::DownloadDataFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::catec_actions_msgs::DownloadDataFeedback_<ContainerAllocator> & v) 
  {
    s << indent << "images_sent: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.images_sent);
    s << indent << "bytes_sent: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.bytes_sent);
  }
};


} // namespace message_operations
} // namespace ros

#endif // CATEC_ACTIONS_MSGS_MESSAGE_DOWNLOADDATAFEEDBACK_H

