/* Auto-generated by genmsg_cpp for file /home/bardo91/programing/ROS-CATEC/CATEC_dataTypes/catec_actions_msgs/msg/PathGoal.msg */
#ifndef CATEC_ACTIONS_MSGS_MESSAGE_PATHGOAL_H
#define CATEC_ACTIONS_MSGS_MESSAGE_PATHGOAL_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "catec_msgs/Position.h"
#include "catec_msgs/Position.h"

namespace catec_actions_msgs
{
template <class ContainerAllocator>
struct PathGoal_ {
  typedef PathGoal_<ContainerAllocator> Type;

  PathGoal_()
  : initial_position()
  , final_position()
  {
  }

  PathGoal_(const ContainerAllocator& _alloc)
  : initial_position(_alloc)
  , final_position(_alloc)
  {
  }

  typedef  ::catec_msgs::Position_<ContainerAllocator>  _initial_position_type;
   ::catec_msgs::Position_<ContainerAllocator>  initial_position;

  typedef  ::catec_msgs::Position_<ContainerAllocator>  _final_position_type;
   ::catec_msgs::Position_<ContainerAllocator>  final_position;


  typedef boost::shared_ptr< ::catec_actions_msgs::PathGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::catec_actions_msgs::PathGoal_<ContainerAllocator>  const> ConstPtr;
}; // struct PathGoal
typedef  ::catec_actions_msgs::PathGoal_<std::allocator<void> > PathGoal;

typedef boost::shared_ptr< ::catec_actions_msgs::PathGoal> PathGoalPtr;
typedef boost::shared_ptr< ::catec_actions_msgs::PathGoal const> PathGoalConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::catec_actions_msgs::PathGoal_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::catec_actions_msgs::PathGoal_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace catec_actions_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::catec_actions_msgs::PathGoal_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::catec_actions_msgs::PathGoal_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::catec_actions_msgs::PathGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "987187562942dbd0b5b93849ed4a5345";
  }

  static const char* value(const  ::catec_actions_msgs::PathGoal_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x987187562942dbd0ULL;
  static const uint64_t static_value2 = 0xb5b93849ed4a5345ULL;
};

template<class ContainerAllocator>
struct DataType< ::catec_actions_msgs::PathGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "catec_actions_msgs/PathGoal";
  }

  static const char* value(const  ::catec_actions_msgs::PathGoal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::catec_actions_msgs::PathGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal definition\n\
catec_msgs/Position initial_position\n\
catec_msgs/Position final_position\n\
\n\
================================================================================\n\
MSG: catec_msgs/Position\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const  ::catec_actions_msgs::PathGoal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::catec_actions_msgs::PathGoal_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::catec_actions_msgs::PathGoal_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.initial_position);
    stream.next(m.final_position);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct PathGoal_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::catec_actions_msgs::PathGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::catec_actions_msgs::PathGoal_<ContainerAllocator> & v) 
  {
    s << indent << "initial_position: ";
s << std::endl;
    Printer< ::catec_msgs::Position_<ContainerAllocator> >::stream(s, indent + "  ", v.initial_position);
    s << indent << "final_position: ";
s << std::endl;
    Printer< ::catec_msgs::Position_<ContainerAllocator> >::stream(s, indent + "  ", v.final_position);
  }
};


} // namespace message_operations
} // namespace ros

#endif // CATEC_ACTIONS_MSGS_MESSAGE_PATHGOAL_H

