/* Auto-generated by genmsg_cpp for file /home/bardo91/programing/ROS-CATEC/CATEC_dataTypes/catec_actions_msgs/msg/ScientificResult.msg */
#ifndef CATEC_ACTIONS_MSGS_MESSAGE_SCIENTIFICRESULT_H
#define CATEC_ACTIONS_MSGS_MESSAGE_SCIENTIFICRESULT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace catec_actions_msgs
{
template <class ContainerAllocator>
struct ScientificResult_ {
  typedef ScientificResult_<ContainerAllocator> Type;

  ScientificResult_()
  : total_images(0)
  , total_bytes(0)
  {
  }

  ScientificResult_(const ContainerAllocator& _alloc)
  : total_images(0)
  , total_bytes(0)
  {
  }

  typedef uint8_t _total_images_type;
  uint8_t total_images;

  typedef uint32_t _total_bytes_type;
  uint32_t total_bytes;


  typedef boost::shared_ptr< ::catec_actions_msgs::ScientificResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::catec_actions_msgs::ScientificResult_<ContainerAllocator>  const> ConstPtr;
}; // struct ScientificResult
typedef  ::catec_actions_msgs::ScientificResult_<std::allocator<void> > ScientificResult;

typedef boost::shared_ptr< ::catec_actions_msgs::ScientificResult> ScientificResultPtr;
typedef boost::shared_ptr< ::catec_actions_msgs::ScientificResult const> ScientificResultConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::catec_actions_msgs::ScientificResult_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::catec_actions_msgs::ScientificResult_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace catec_actions_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::catec_actions_msgs::ScientificResult_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::catec_actions_msgs::ScientificResult_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::catec_actions_msgs::ScientificResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "e18ca942bc9561a8aba7333c2de9ed68";
  }

  static const char* value(const  ::catec_actions_msgs::ScientificResult_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xe18ca942bc9561a8ULL;
  static const uint64_t static_value2 = 0xaba7333c2de9ed68ULL;
};

template<class ContainerAllocator>
struct DataType< ::catec_actions_msgs::ScientificResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "catec_actions_msgs/ScientificResult";
  }

  static const char* value(const  ::catec_actions_msgs::ScientificResult_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::catec_actions_msgs::ScientificResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#result definition\n\
uint8 total_images\n\
uint32 total_bytes\n\
\n\
";
  }

  static const char* value(const  ::catec_actions_msgs::ScientificResult_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::catec_actions_msgs::ScientificResult_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::catec_actions_msgs::ScientificResult_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.total_images);
    stream.next(m.total_bytes);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ScientificResult_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::catec_actions_msgs::ScientificResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::catec_actions_msgs::ScientificResult_<ContainerAllocator> & v) 
  {
    s << indent << "total_images: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.total_images);
    s << indent << "total_bytes: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.total_bytes);
  }
};


} // namespace message_operations
} // namespace ros

#endif // CATEC_ACTIONS_MSGS_MESSAGE_SCIENTIFICRESULT_H

