/* Auto-generated by genmsg_cpp for file /home/bardo91/programing/ROS-CATEC/CATEC_dataTypes/catec_actions_msgs/msg/ScientificGoal.msg */
#ifndef CATEC_ACTIONS_MSGS_MESSAGE_SCIENTIFICGOAL_H
#define CATEC_ACTIONS_MSGS_MESSAGE_SCIENTIFICGOAL_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace catec_actions_msgs
{
template <class ContainerAllocator>
struct ScientificGoal_ {
  typedef ScientificGoal_<ContainerAllocator> Type;

  ScientificGoal_()
  : number_of_images(0)
  {
  }

  ScientificGoal_(const ContainerAllocator& _alloc)
  : number_of_images(0)
  {
  }

  typedef uint8_t _number_of_images_type;
  uint8_t number_of_images;


  typedef boost::shared_ptr< ::catec_actions_msgs::ScientificGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::catec_actions_msgs::ScientificGoal_<ContainerAllocator>  const> ConstPtr;
}; // struct ScientificGoal
typedef  ::catec_actions_msgs::ScientificGoal_<std::allocator<void> > ScientificGoal;

typedef boost::shared_ptr< ::catec_actions_msgs::ScientificGoal> ScientificGoalPtr;
typedef boost::shared_ptr< ::catec_actions_msgs::ScientificGoal const> ScientificGoalConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::catec_actions_msgs::ScientificGoal_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::catec_actions_msgs::ScientificGoal_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace catec_actions_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::catec_actions_msgs::ScientificGoal_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::catec_actions_msgs::ScientificGoal_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::catec_actions_msgs::ScientificGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "41f4f33d494faee3ed1336105d621dc6";
  }

  static const char* value(const  ::catec_actions_msgs::ScientificGoal_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x41f4f33d494faee3ULL;
  static const uint64_t static_value2 = 0xed1336105d621dc6ULL;
};

template<class ContainerAllocator>
struct DataType< ::catec_actions_msgs::ScientificGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "catec_actions_msgs/ScientificGoal";
  }

  static const char* value(const  ::catec_actions_msgs::ScientificGoal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::catec_actions_msgs::ScientificGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal definition\n\
uint8 number_of_images\n\
\n\
";
  }

  static const char* value(const  ::catec_actions_msgs::ScientificGoal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::catec_actions_msgs::ScientificGoal_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::catec_actions_msgs::ScientificGoal_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.number_of_images);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ScientificGoal_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::catec_actions_msgs::ScientificGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::catec_actions_msgs::ScientificGoal_<ContainerAllocator> & v) 
  {
    s << indent << "number_of_images: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.number_of_images);
  }
};


} // namespace message_operations
} // namespace ros

#endif // CATEC_ACTIONS_MSGS_MESSAGE_SCIENTIFICGOAL_H

