/* Auto-generated by genmsg_cpp for file /home/bardo91/programing/ROS-CATEC/CATEC_dataTypes/catec_actions_msgs/msg/ScientificFeedback.msg */
#ifndef CATEC_ACTIONS_MSGS_MESSAGE_SCIENTIFICFEEDBACK_H
#define CATEC_ACTIONS_MSGS_MESSAGE_SCIENTIFICFEEDBACK_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace catec_actions_msgs
{
template <class ContainerAllocator>
struct ScientificFeedback_ {
  typedef ScientificFeedback_<ContainerAllocator> Type;

  ScientificFeedback_()
  : remaining_images(0)
  , actual_bytes(0)
  {
  }

  ScientificFeedback_(const ContainerAllocator& _alloc)
  : remaining_images(0)
  , actual_bytes(0)
  {
  }

  typedef uint8_t _remaining_images_type;
  uint8_t remaining_images;

  typedef uint32_t _actual_bytes_type;
  uint32_t actual_bytes;


  typedef boost::shared_ptr< ::catec_actions_msgs::ScientificFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::catec_actions_msgs::ScientificFeedback_<ContainerAllocator>  const> ConstPtr;
}; // struct ScientificFeedback
typedef  ::catec_actions_msgs::ScientificFeedback_<std::allocator<void> > ScientificFeedback;

typedef boost::shared_ptr< ::catec_actions_msgs::ScientificFeedback> ScientificFeedbackPtr;
typedef boost::shared_ptr< ::catec_actions_msgs::ScientificFeedback const> ScientificFeedbackConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::catec_actions_msgs::ScientificFeedback_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::catec_actions_msgs::ScientificFeedback_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace catec_actions_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::catec_actions_msgs::ScientificFeedback_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::catec_actions_msgs::ScientificFeedback_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::catec_actions_msgs::ScientificFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "6edeaeb04595610ee20420c2cd6dd575";
  }

  static const char* value(const  ::catec_actions_msgs::ScientificFeedback_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x6edeaeb04595610eULL;
  static const uint64_t static_value2 = 0xe20420c2cd6dd575ULL;
};

template<class ContainerAllocator>
struct DataType< ::catec_actions_msgs::ScientificFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "catec_actions_msgs/ScientificFeedback";
  }

  static const char* value(const  ::catec_actions_msgs::ScientificFeedback_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::catec_actions_msgs::ScientificFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#feedback definition\n\
uint8  remaining_images\n\
uint32 actual_bytes\n\
\n\
\n\
";
  }

  static const char* value(const  ::catec_actions_msgs::ScientificFeedback_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::catec_actions_msgs::ScientificFeedback_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::catec_actions_msgs::ScientificFeedback_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.remaining_images);
    stream.next(m.actual_bytes);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ScientificFeedback_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::catec_actions_msgs::ScientificFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::catec_actions_msgs::ScientificFeedback_<ContainerAllocator> & v) 
  {
    s << indent << "remaining_images: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.remaining_images);
    s << indent << "actual_bytes: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.actual_bytes);
  }
};


} // namespace message_operations
} // namespace ros

#endif // CATEC_ACTIONS_MSGS_MESSAGE_SCIENTIFICFEEDBACK_H

