/* Auto-generated by genmsg_cpp for file /home/bardo91/programing/ROS-CATEC/CATEC_dataTypes/catec_actions_msgs/msg/TargetGoal.msg */
#ifndef CATEC_ACTIONS_MSGS_MESSAGE_TARGETGOAL_H
#define CATEC_ACTIONS_MSGS_MESSAGE_TARGETGOAL_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace catec_actions_msgs
{
template <class ContainerAllocator>
struct TargetGoal_ {
  typedef TargetGoal_<ContainerAllocator> Type;

  TargetGoal_()
  : target_type(0)
  {
  }

  TargetGoal_(const ContainerAllocator& _alloc)
  : target_type(0)
  {
  }

  typedef uint8_t _target_type_type;
  uint8_t target_type;


  typedef boost::shared_ptr< ::catec_actions_msgs::TargetGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::catec_actions_msgs::TargetGoal_<ContainerAllocator>  const> ConstPtr;
}; // struct TargetGoal
typedef  ::catec_actions_msgs::TargetGoal_<std::allocator<void> > TargetGoal;

typedef boost::shared_ptr< ::catec_actions_msgs::TargetGoal> TargetGoalPtr;
typedef boost::shared_ptr< ::catec_actions_msgs::TargetGoal const> TargetGoalConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::catec_actions_msgs::TargetGoal_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::catec_actions_msgs::TargetGoal_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace catec_actions_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::catec_actions_msgs::TargetGoal_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::catec_actions_msgs::TargetGoal_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::catec_actions_msgs::TargetGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "30e4bf265ec1bc3bdf54416d26ab5450";
  }

  static const char* value(const  ::catec_actions_msgs::TargetGoal_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x30e4bf265ec1bc3bULL;
  static const uint64_t static_value2 = 0xdf54416d26ab5450ULL;
};

template<class ContainerAllocator>
struct DataType< ::catec_actions_msgs::TargetGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "catec_actions_msgs/TargetGoal";
  }

  static const char* value(const  ::catec_actions_msgs::TargetGoal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::catec_actions_msgs::TargetGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal definition\n\
uint8 target_type\n\
\n\
";
  }

  static const char* value(const  ::catec_actions_msgs::TargetGoal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::catec_actions_msgs::TargetGoal_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::catec_actions_msgs::TargetGoal_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.target_type);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct TargetGoal_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::catec_actions_msgs::TargetGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::catec_actions_msgs::TargetGoal_<ContainerAllocator> & v) 
  {
    s << indent << "target_type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.target_type);
  }
};


} // namespace message_operations
} // namespace ros

#endif // CATEC_ACTIONS_MSGS_MESSAGE_TARGETGOAL_H

