/* Auto-generated by genmsg_cpp for file /home/bardo91/programing/ROS-CATEC/CATEC_dataTypes/catec_msgs/msg/AALStateStamped.msg */
#ifndef CATEC_MSGS_MESSAGE_AALSTATESTAMPED_H
#define CATEC_MSGS_MESSAGE_AALSTATESTAMPED_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"
#include "catec_msgs/AALState.h"

namespace catec_msgs
{
template <class ContainerAllocator>
struct AALStateStamped_ {
  typedef AALStateStamped_<ContainerAllocator> Type;

  AALStateStamped_()
  : header()
  , aal_state()
  {
  }

  AALStateStamped_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , aal_state(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef  ::catec_msgs::AALState_<ContainerAllocator>  _aal_state_type;
   ::catec_msgs::AALState_<ContainerAllocator>  aal_state;


  typedef boost::shared_ptr< ::catec_msgs::AALStateStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::catec_msgs::AALStateStamped_<ContainerAllocator>  const> ConstPtr;
}; // struct AALStateStamped
typedef  ::catec_msgs::AALStateStamped_<std::allocator<void> > AALStateStamped;

typedef boost::shared_ptr< ::catec_msgs::AALStateStamped> AALStateStampedPtr;
typedef boost::shared_ptr< ::catec_msgs::AALStateStamped const> AALStateStampedConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::catec_msgs::AALStateStamped_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::catec_msgs::AALStateStamped_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace catec_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::catec_msgs::AALStateStamped_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::catec_msgs::AALStateStamped_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::catec_msgs::AALStateStamped_<ContainerAllocator> > {
  static const char* value() 
  {
    return "7b1ea4361ddb6c11eb8e27c329722803";
  }

  static const char* value(const  ::catec_msgs::AALStateStamped_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x7b1ea4361ddb6c11ULL;
  static const uint64_t static_value2 = 0xeb8e27c329722803ULL;
};

template<class ContainerAllocator>
struct DataType< ::catec_msgs::AALStateStamped_<ContainerAllocator> > {
  static const char* value() 
  {
    return "catec_msgs/AALStateStamped";
  }

  static const char* value(const  ::catec_msgs::AALStateStamped_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::catec_msgs::AALStateStamped_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
AALState aal_state\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: catec_msgs/AALState\n\
uint8 CONTRACTED=1\n\
uint8 CONTRACTING=1\n\
uint8 EXTENDED=1\n\
uint8 EXTENDING=1\n\
uint8 state\n\
Position final_effector_position\n\
Orientation final_effector_orientation\n\
float64    claw\n\
float64[6] joints_angles\n\
\n\
\n\
\n\
================================================================================\n\
MSG: catec_msgs/Position\n\
float64 x\n\
float64 y\n\
float64 z\n\
================================================================================\n\
MSG: catec_msgs/Orientation\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const  ::catec_msgs::AALStateStamped_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::catec_msgs::AALStateStamped_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::catec_msgs::AALStateStamped_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::catec_msgs::AALStateStamped_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.aal_state);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct AALStateStamped_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::catec_msgs::AALStateStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::catec_msgs::AALStateStamped_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "aal_state: ";
s << std::endl;
    Printer< ::catec_msgs::AALState_<ContainerAllocator> >::stream(s, indent + "  ", v.aal_state);
  }
};


} // namespace message_operations
} // namespace ros

#endif // CATEC_MSGS_MESSAGE_AALSTATESTAMPED_H

