/* Auto-generated by genmsg_cpp for file /home/bardo91/programing/ROS-CATEC/CATEC_dataTypes/catec_msgs/msg/DayNight.msg */
#ifndef CATEC_MSGS_MESSAGE_DAYNIGHT_H
#define CATEC_MSGS_MESSAGE_DAYNIGHT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace catec_msgs
{
template <class ContainerAllocator>
struct DayNight_ {
  typedef DayNight_<ContainerAllocator> Type;

  DayNight_()
  : now()
  , is_day_light(false)
  , days(0)
  {
  }

  DayNight_(const ContainerAllocator& _alloc)
  : now()
  , is_day_light(false)
  , days(0)
  {
  }

  typedef ros::Time _now_type;
  ros::Time now;

  typedef uint8_t _is_day_light_type;
  uint8_t is_day_light;

  typedef int32_t _days_type;
  int32_t days;


  typedef boost::shared_ptr< ::catec_msgs::DayNight_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::catec_msgs::DayNight_<ContainerAllocator>  const> ConstPtr;
}; // struct DayNight
typedef  ::catec_msgs::DayNight_<std::allocator<void> > DayNight;

typedef boost::shared_ptr< ::catec_msgs::DayNight> DayNightPtr;
typedef boost::shared_ptr< ::catec_msgs::DayNight const> DayNightConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::catec_msgs::DayNight_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::catec_msgs::DayNight_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace catec_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::catec_msgs::DayNight_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::catec_msgs::DayNight_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::catec_msgs::DayNight_<ContainerAllocator> > {
  static const char* value() 
  {
    return "1938393faac749502c696eb029a7c7ec";
  }

  static const char* value(const  ::catec_msgs::DayNight_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x1938393faac74950ULL;
  static const uint64_t static_value2 = 0x2c696eb029a7c7ecULL;
};

template<class ContainerAllocator>
struct DataType< ::catec_msgs::DayNight_<ContainerAllocator> > {
  static const char* value() 
  {
    return "catec_msgs/DayNight";
  }

  static const char* value(const  ::catec_msgs::DayNight_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::catec_msgs::DayNight_<ContainerAllocator> > {
  static const char* value() 
  {
    return "time now\n\
bool is_day_light\n\
int32 days\n\
\n\
";
  }

  static const char* value(const  ::catec_msgs::DayNight_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::catec_msgs::DayNight_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::catec_msgs::DayNight_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.now);
    stream.next(m.is_day_light);
    stream.next(m.days);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct DayNight_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::catec_msgs::DayNight_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::catec_msgs::DayNight_<ContainerAllocator> & v) 
  {
    s << indent << "now: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.now);
    s << indent << "is_day_light: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_day_light);
    s << indent << "days: ";
    Printer<int32_t>::stream(s, indent + "  ", v.days);
  }
};


} // namespace message_operations
} // namespace ros

#endif // CATEC_MSGS_MESSAGE_DAYNIGHT_H

