/* Auto-generated by genmsg_cpp for file /home/bardo91/programing/ROS-CATEC/CATEC_dataTypes/catec_msgs/msg/DynamicState.msg */
#ifndef CATEC_MSGS_MESSAGE_DYNAMICSTATE_H
#define CATEC_MSGS_MESSAGE_DYNAMICSTATE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "catec_msgs/PositionWithCheck.h"
#include "catec_msgs/OrientationWithCheck.h"
#include "catec_msgs/VelocityWithCheck.h"

namespace catec_msgs
{
template <class ContainerAllocator>
struct DynamicState_ {
  typedef DynamicState_<ContainerAllocator> Type;

  DynamicState_()
  : position()
  , orientation()
  , velocity()
  {
  }

  DynamicState_(const ContainerAllocator& _alloc)
  : position(_alloc)
  , orientation(_alloc)
  , velocity(_alloc)
  {
  }

  typedef  ::catec_msgs::PositionWithCheck_<ContainerAllocator>  _position_type;
   ::catec_msgs::PositionWithCheck_<ContainerAllocator>  position;

  typedef  ::catec_msgs::OrientationWithCheck_<ContainerAllocator>  _orientation_type;
   ::catec_msgs::OrientationWithCheck_<ContainerAllocator>  orientation;

  typedef  ::catec_msgs::VelocityWithCheck_<ContainerAllocator>  _velocity_type;
   ::catec_msgs::VelocityWithCheck_<ContainerAllocator>  velocity;


  typedef boost::shared_ptr< ::catec_msgs::DynamicState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::catec_msgs::DynamicState_<ContainerAllocator>  const> ConstPtr;
}; // struct DynamicState
typedef  ::catec_msgs::DynamicState_<std::allocator<void> > DynamicState;

typedef boost::shared_ptr< ::catec_msgs::DynamicState> DynamicStatePtr;
typedef boost::shared_ptr< ::catec_msgs::DynamicState const> DynamicStateConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::catec_msgs::DynamicState_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::catec_msgs::DynamicState_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace catec_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::catec_msgs::DynamicState_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::catec_msgs::DynamicState_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::catec_msgs::DynamicState_<ContainerAllocator> > {
  static const char* value() 
  {
    return "cef369e150c278d36d30afc4228349b1";
  }

  static const char* value(const  ::catec_msgs::DynamicState_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xcef369e150c278d3ULL;
  static const uint64_t static_value2 = 0x6d30afc4228349b1ULL;
};

template<class ContainerAllocator>
struct DataType< ::catec_msgs::DynamicState_<ContainerAllocator> > {
  static const char* value() 
  {
    return "catec_msgs/DynamicState";
  }

  static const char* value(const  ::catec_msgs::DynamicState_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::catec_msgs::DynamicState_<ContainerAllocator> > {
  static const char* value() 
  {
    return "PositionWithCheck position\n\
OrientationWithCheck orientation\n\
VelocityWithCheck velocity\n\
================================================================================\n\
MSG: catec_msgs/PositionWithCheck\n\
float64 x\n\
float64 y\n\
float64 z\n\
uint8 valid\n\
================================================================================\n\
MSG: catec_msgs/OrientationWithCheck\n\
float64 x\n\
float64 y\n\
float64 z\n\
uint8 valid\n\
================================================================================\n\
MSG: catec_msgs/VelocityWithCheck\n\
float64 x\n\
float64 y\n\
float64 z\n\
uint8 valid\n\
";
  }

  static const char* value(const  ::catec_msgs::DynamicState_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::catec_msgs::DynamicState_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::catec_msgs::DynamicState_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.position);
    stream.next(m.orientation);
    stream.next(m.velocity);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct DynamicState_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::catec_msgs::DynamicState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::catec_msgs::DynamicState_<ContainerAllocator> & v) 
  {
    s << indent << "position: ";
s << std::endl;
    Printer< ::catec_msgs::PositionWithCheck_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "orientation: ";
s << std::endl;
    Printer< ::catec_msgs::OrientationWithCheck_<ContainerAllocator> >::stream(s, indent + "  ", v.orientation);
    s << indent << "velocity: ";
s << std::endl;
    Printer< ::catec_msgs::VelocityWithCheck_<ContainerAllocator> >::stream(s, indent + "  ", v.velocity);
  }
};


} // namespace message_operations
} // namespace ros

#endif // CATEC_MSGS_MESSAGE_DYNAMICSTATE_H

