/* Auto-generated by genmsg_cpp for file /home/bardo91/programing/ROS-CATEC/CATEC_dataTypes/catec_msgs/msg/ScientificInfo.msg */
#ifndef CATEC_MSGS_MESSAGE_SCIENTIFICINFO_H
#define CATEC_MSGS_MESSAGE_SCIENTIFICINFO_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace catec_msgs
{
template <class ContainerAllocator>
struct ScientificInfo_ {
  typedef ScientificInfo_<ContainerAllocator> Type;

  ScientificInfo_()
  : enable(false)
  , remaining_bytes(0)
  {
  }

  ScientificInfo_(const ContainerAllocator& _alloc)
  : enable(false)
  , remaining_bytes(0)
  {
  }

  typedef uint8_t _enable_type;
  uint8_t enable;

  typedef uint32_t _remaining_bytes_type;
  uint32_t remaining_bytes;


  typedef boost::shared_ptr< ::catec_msgs::ScientificInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::catec_msgs::ScientificInfo_<ContainerAllocator>  const> ConstPtr;
}; // struct ScientificInfo
typedef  ::catec_msgs::ScientificInfo_<std::allocator<void> > ScientificInfo;

typedef boost::shared_ptr< ::catec_msgs::ScientificInfo> ScientificInfoPtr;
typedef boost::shared_ptr< ::catec_msgs::ScientificInfo const> ScientificInfoConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::catec_msgs::ScientificInfo_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::catec_msgs::ScientificInfo_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace catec_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::catec_msgs::ScientificInfo_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::catec_msgs::ScientificInfo_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::catec_msgs::ScientificInfo_<ContainerAllocator> > {
  static const char* value() 
  {
    return "77b9ad55d3a68a2b20d893990522f884";
  }

  static const char* value(const  ::catec_msgs::ScientificInfo_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x77b9ad55d3a68a2bULL;
  static const uint64_t static_value2 = 0x20d893990522f884ULL;
};

template<class ContainerAllocator>
struct DataType< ::catec_msgs::ScientificInfo_<ContainerAllocator> > {
  static const char* value() 
  {
    return "catec_msgs/ScientificInfo";
  }

  static const char* value(const  ::catec_msgs::ScientificInfo_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::catec_msgs::ScientificInfo_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bool enable\n\
uint32 remaining_bytes\n\
\n\
";
  }

  static const char* value(const  ::catec_msgs::ScientificInfo_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::catec_msgs::ScientificInfo_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::catec_msgs::ScientificInfo_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.enable);
    stream.next(m.remaining_bytes);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ScientificInfo_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::catec_msgs::ScientificInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::catec_msgs::ScientificInfo_<ContainerAllocator> & v) 
  {
    s << indent << "enable: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enable);
    s << indent << "remaining_bytes: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.remaining_bytes);
  }
};


} // namespace message_operations
} // namespace ros

#endif // CATEC_MSGS_MESSAGE_SCIENTIFICINFO_H

