/* Auto-generated by genmsg_cpp for file /home/bardo91/programing/ROS-CATEC/CATEC_dataTypes/catec_msgs/msg/TimePriorityCollisionPoint.msg */
#ifndef CATEC_MSGS_MESSAGE_TIMEPRIORITYCOLLISIONPOINT_H
#define CATEC_MSGS_MESSAGE_TIMEPRIORITYCOLLISIONPOINT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace catec_msgs
{
template <class ContainerAllocator>
struct TimePriorityCollisionPoint_ {
  typedef TimePriorityCollisionPoint_<ContainerAllocator> Type;

  TimePriorityCollisionPoint_()
  : x(0.0)
  , y(0.0)
  , z(0.0)
  , priority(0)
  , time(0)
  {
  }

  TimePriorityCollisionPoint_(const ContainerAllocator& _alloc)
  : x(0.0)
  , y(0.0)
  , z(0.0)
  , priority(0)
  , time(0)
  {
  }

  typedef double _x_type;
  double x;

  typedef double _y_type;
  double y;

  typedef double _z_type;
  double z;

  typedef uint8_t _priority_type;
  uint8_t priority;

  typedef uint32_t _time_type;
  uint32_t time;


  typedef boost::shared_ptr< ::catec_msgs::TimePriorityCollisionPoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::catec_msgs::TimePriorityCollisionPoint_<ContainerAllocator>  const> ConstPtr;
}; // struct TimePriorityCollisionPoint
typedef  ::catec_msgs::TimePriorityCollisionPoint_<std::allocator<void> > TimePriorityCollisionPoint;

typedef boost::shared_ptr< ::catec_msgs::TimePriorityCollisionPoint> TimePriorityCollisionPointPtr;
typedef boost::shared_ptr< ::catec_msgs::TimePriorityCollisionPoint const> TimePriorityCollisionPointConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::catec_msgs::TimePriorityCollisionPoint_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::catec_msgs::TimePriorityCollisionPoint_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace catec_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::catec_msgs::TimePriorityCollisionPoint_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::catec_msgs::TimePriorityCollisionPoint_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::catec_msgs::TimePriorityCollisionPoint_<ContainerAllocator> > {
  static const char* value() 
  {
    return "1add2fa68080a7a823b192cee01ae413";
  }

  static const char* value(const  ::catec_msgs::TimePriorityCollisionPoint_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x1add2fa68080a7a8ULL;
  static const uint64_t static_value2 = 0x23b192cee01ae413ULL;
};

template<class ContainerAllocator>
struct DataType< ::catec_msgs::TimePriorityCollisionPoint_<ContainerAllocator> > {
  static const char* value() 
  {
    return "catec_msgs/TimePriorityCollisionPoint";
  }

  static const char* value(const  ::catec_msgs::TimePriorityCollisionPoint_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::catec_msgs::TimePriorityCollisionPoint_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float64 x\n\
float64 y\n\
float64 z\n\
uint8 priority\n\
uint32 time\n\
\n\
";
  }

  static const char* value(const  ::catec_msgs::TimePriorityCollisionPoint_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::catec_msgs::TimePriorityCollisionPoint_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::catec_msgs::TimePriorityCollisionPoint_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.x);
    stream.next(m.y);
    stream.next(m.z);
    stream.next(m.priority);
    stream.next(m.time);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct TimePriorityCollisionPoint_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::catec_msgs::TimePriorityCollisionPoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::catec_msgs::TimePriorityCollisionPoint_<ContainerAllocator> & v) 
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "priority: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.priority);
    s << indent << "time: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.time);
  }
};


} // namespace message_operations
} // namespace ros

#endif // CATEC_MSGS_MESSAGE_TIMEPRIORITYCOLLISIONPOINT_H

