/* Auto-generated by genmsg_cpp for file /home/bardo91/programing/ROS-CATEC/CATEC_dataTypes/catec_msgs/msg/WayPoint.msg */
#ifndef CATEC_MSGS_MESSAGE_WAYPOINT_H
#define CATEC_MSGS_MESSAGE_WAYPOINT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace catec_msgs
{
template <class ContainerAllocator>
struct WayPoint_ {
  typedef WayPoint_<ContainerAllocator> Type;

  WayPoint_()
  : x(0.0)
  , y(0.0)
  , z(0.0)
  , heading(0.0)
  {
  }

  WayPoint_(const ContainerAllocator& _alloc)
  : x(0.0)
  , y(0.0)
  , z(0.0)
  , heading(0.0)
  {
  }

  typedef double _x_type;
  double x;

  typedef double _y_type;
  double y;

  typedef double _z_type;
  double z;

  typedef double _heading_type;
  double heading;


  typedef boost::shared_ptr< ::catec_msgs::WayPoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::catec_msgs::WayPoint_<ContainerAllocator>  const> ConstPtr;
}; // struct WayPoint
typedef  ::catec_msgs::WayPoint_<std::allocator<void> > WayPoint;

typedef boost::shared_ptr< ::catec_msgs::WayPoint> WayPointPtr;
typedef boost::shared_ptr< ::catec_msgs::WayPoint const> WayPointConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::catec_msgs::WayPoint_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::catec_msgs::WayPoint_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace catec_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::catec_msgs::WayPoint_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::catec_msgs::WayPoint_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::catec_msgs::WayPoint_<ContainerAllocator> > {
  static const char* value() 
  {
    return "a0c8bbbba51f36b9c247a3a067516a8a";
  }

  static const char* value(const  ::catec_msgs::WayPoint_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xa0c8bbbba51f36b9ULL;
  static const uint64_t static_value2 = 0xc247a3a067516a8aULL;
};

template<class ContainerAllocator>
struct DataType< ::catec_msgs::WayPoint_<ContainerAllocator> > {
  static const char* value() 
  {
    return "catec_msgs/WayPoint";
  }

  static const char* value(const  ::catec_msgs::WayPoint_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::catec_msgs::WayPoint_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float64 x\n\
float64 y\n\
float64 z\n\
float64 heading\n\
";
  }

  static const char* value(const  ::catec_msgs::WayPoint_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::catec_msgs::WayPoint_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::catec_msgs::WayPoint_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.x);
    stream.next(m.y);
    stream.next(m.z);
    stream.next(m.heading);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct WayPoint_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::catec_msgs::WayPoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::catec_msgs::WayPoint_<ContainerAllocator> & v) 
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "heading: ";
    Printer<double>::stream(s, indent + "  ", v.heading);
  }
};


} // namespace message_operations
} // namespace ros

#endif // CATEC_MSGS_MESSAGE_WAYPOINT_H

