/* Auto-generated by genmsg_cpp for file /home/bardo91/programing/ROS-CATEC/CATEC_dataTypes/catec_msgs/msg/WayPointWithCruiseStamped.msg */
#ifndef CATEC_MSGS_MESSAGE_WAYPOINTWITHCRUISESTAMPED_H
#define CATEC_MSGS_MESSAGE_WAYPOINTWITHCRUISESTAMPED_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"
#include "catec_msgs/WayPointWithCruise.h"

namespace catec_msgs
{
template <class ContainerAllocator>
struct WayPointWithCruiseStamped_ {
  typedef WayPointWithCruiseStamped_<ContainerAllocator> Type;

  WayPointWithCruiseStamped_()
  : header()
  , way_point()
  {
  }

  WayPointWithCruiseStamped_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , way_point(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef  ::catec_msgs::WayPointWithCruise_<ContainerAllocator>  _way_point_type;
   ::catec_msgs::WayPointWithCruise_<ContainerAllocator>  way_point;


  typedef boost::shared_ptr< ::catec_msgs::WayPointWithCruiseStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::catec_msgs::WayPointWithCruiseStamped_<ContainerAllocator>  const> ConstPtr;
}; // struct WayPointWithCruiseStamped
typedef  ::catec_msgs::WayPointWithCruiseStamped_<std::allocator<void> > WayPointWithCruiseStamped;

typedef boost::shared_ptr< ::catec_msgs::WayPointWithCruiseStamped> WayPointWithCruiseStampedPtr;
typedef boost::shared_ptr< ::catec_msgs::WayPointWithCruiseStamped const> WayPointWithCruiseStampedConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::catec_msgs::WayPointWithCruiseStamped_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::catec_msgs::WayPointWithCruiseStamped_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace catec_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::catec_msgs::WayPointWithCruiseStamped_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::catec_msgs::WayPointWithCruiseStamped_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::catec_msgs::WayPointWithCruiseStamped_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d45499caf015a274d58cfecd8814ee6f";
  }

  static const char* value(const  ::catec_msgs::WayPointWithCruiseStamped_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd45499caf015a274ULL;
  static const uint64_t static_value2 = 0xd58cfecd8814ee6fULL;
};

template<class ContainerAllocator>
struct DataType< ::catec_msgs::WayPointWithCruiseStamped_<ContainerAllocator> > {
  static const char* value() 
  {
    return "catec_msgs/WayPointWithCruiseStamped";
  }

  static const char* value(const  ::catec_msgs::WayPointWithCruiseStamped_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::catec_msgs::WayPointWithCruiseStamped_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
WayPointWithCruise way_point\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: catec_msgs/WayPointWithCruise\n\
float64 x\n\
float64 y\n\
float64 z\n\
float32 cruise\n\
float64 heading\n\
";
  }

  static const char* value(const  ::catec_msgs::WayPointWithCruiseStamped_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::catec_msgs::WayPointWithCruiseStamped_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::catec_msgs::WayPointWithCruiseStamped_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::catec_msgs::WayPointWithCruiseStamped_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.way_point);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct WayPointWithCruiseStamped_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::catec_msgs::WayPointWithCruiseStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::catec_msgs::WayPointWithCruiseStamped_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "way_point: ";
s << std::endl;
    Printer< ::catec_msgs::WayPointWithCruise_<ContainerAllocator> >::stream(s, indent + "  ", v.way_point);
  }
};


} // namespace message_operations
} // namespace ros

#endif // CATEC_MSGS_MESSAGE_WAYPOINTWITHCRUISESTAMPED_H

